#!/bin/bash

# echo
./minishell 'echo > output'
./minishell 'echo "" >> output'
./minishell 'echo < | >> output'
./minishell 'echo > | >> output'
./minishell 'echo << | >> output'
./minishell 'echo >> | >> output'
./minishell 'echo -nABC >> output'
./minishell 'echo $BLA$BLA=10$BLA >> output'
./minishell 'echo a"bc"d >> output'
./minishell 'echo a"bcd"e >> output'
./minishell "echo 'hoi'"'"bla" >> output'
./minishell 'echo -n >> output'
./minishell 'echo bla -n >> output'
./minishell 'echo -n -n -n >> output'
./minishell 'echo -n -n -n bla >> output'
./minishell 'ls | echo -n bla >> output'
./minishell 'echo -nnnn >> output'
./minishell 'echo -nnnn bla >> output'

./minishell 'echo >> output'
./minishell 'echo >> output'

# pwd
./minishell 'pwd >> output'
./minishell 'pwd lalala >> output'

# cd
./minishell 'echo >> output'
./minishell 'cd\npwd >> output'
./minishell 'cd\npwd\ncd -\npwd >> output'
./minishell 'cd ..\ncd tests\npwd >> output'
./minishell 'cd ..\ncd tests/\npwd >> output'
./minishell 'cd ../../..\npwd >> output'
./minishell 'cd banaan >> output'
./minishell 'cd /usr\npwd >> output'
./minishell 'cd /usr/bin\npwd >> output'
./minishell 'cd /bla >> output'
./minishell 'cd /\npwd >> output'
./minishell 'cd ..\necho $OLDPWD\ncd tests\necho $OLDPWD >> output'

#
./minishell "echo >> output"
./minishell 'echo "*" >> output'
./minishell 'echo *bla >> output'
./minishell "echo '$PATH' >> output"
./minishell 'echo "$     a" >> output'
./minishell 'echo $ >> output'
./minishell 'echo $9 >> output'
./minishell 'echo $9a >> output'
./minishell 'echo $98a >> output'
./minishell 'echo $PA >> output'
./minishell 'echo $PA: >> output'
./minishell 'echo $HOME: >> output'
./minishell 'echo $HOME >> output'
./minishell 'echo "$HOME" >> output'
./minishell 'echo $HO"ME" >> output'
./minishell 'echo $"HOME" >> output'
./minishell 'echo $ "HOME" >> output'
./minishell 'echo '\''$"HOME" >> output'
./minishell 'echo bla $bla >> output'
./minishell 'echo bla $bla | cat -e >> output'

./minishell 'cat '"f'i'l"e"1"' >> output'