#!/bin/bash
# set -x
set -e

shopt -s extglob
mkdir -p objs_san
mkdir -p objs_leaks
mkdir -p bin

cd objs_leaks
gcc -Wall -Wextra -c -g -I.. ../../!(minishe*).c -I $READLINE_DIR/include/
cd ..

make DEBUG=1 LEAKS=1 -C ..
for file in test_expand_unquoted_args.c test_replace.c test_split_unquoted.c test_replace_parts.c test_wildcard.c test_shell_split.c
do
	export BASE=${file%.*}
	echo "checking $BASE"
	gcc -Wall -Wextra -g -L../Libft -I.. $file objs_leaks/*.o -o bin/${file%.*} -lft -I $READLINE_DIR/include/ -L $READLINE_DIR/lib/ -lreadline ../get_next_line/get_next_line.a
	valgrind --leak-check=full bin/${file%.*} > ${file%.*}.check 2>leaks_output
	diff ${file%.*}.check ${file%.*}.out
	cat leaks_output | grep -q ' 0 errors from 0 contexts' || { echo "valgrind errors found!"; cat leaks_output; exit 1; }
done
shopt -u extglob

./integration_tests

echo FINISHED!!!!!
